FROM ubuntu:latest

# update 
RUN apt-get -y update && \
    apt-get install -y nodejs npm

# Network Configuraiton
EXPOSE 3000

# User that will be used.
# USER node

# Set default working directory
RUN mkdir -p /home/node/app
WORKDIR /home/node/app


# Copy package.json and Install the necessary dependencies
COPY ./package.json .
RUN npm install 

# Copy the rest of project files
COPY . .

CMD [ "npm", "run", "dev" ]